[package]
name = "assign-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_lambda_events = "0.6.0"
lambda_runtime = "0.5.0"
log = "0.4.14"
simple_logger = "2.1.0"
tokio = "1.17.0"